# Generated by Django 5.1.5 on 2025-04-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurahProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_ayah', models.IntegerField(default=1)),
                ('completed_count', models.IntegerField(default=0)),
            ],
        ),
    ]
