# Generated by Django 5.2 on 2025-04-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AyahAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayah_number', models.IntegerField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
