# Generated by Django 5.2 on 2025-04-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatm', '0002_ayahassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ayahassignment',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='ayahassignment',
            name='is_used',
        ),
        migrations.AlterField(
            model_name='ayahassignment',
            name='ayah_number',
            field=models.IntegerField(unique=True),
        ),
    ]
